"""empty message

Revision ID: 04c894a35632
Revises: d90e51b4d0b9
Create Date: 2017-03-20 07:17:41.932231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04c894a35632'
down_revision = 'd90e51b4d0b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dimensions', sa.Column('name', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dimensions', 'name')
    # ### end Alembic commands ###
