"""empty message

Revision ID: 09bbaf264203
Revises: cb04a13491dc
Create Date: 2017-03-23 11:00:21.579028

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09bbaf264203'
down_revision = 'cb04a13491dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('observations', sa.Column('date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('observations', 'date')
    # ### end Alembic commands ###
