"""empty message

Revision ID: 18f2c2e888bc
Revises: 76b53d991dee
Create Date: 2017-03-21 19:11:34.052139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18f2c2e888bc'
down_revision = '76b53d991dee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('experiments_for_user')
    op.drop_table('observations_for_experiment')
    op.drop_table('dimensions_for_experiment')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dimensions_for_experiment',
    sa.Column('dimension_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('experiment_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['dimension_id'], ['dimensions.id'], name='dimensions_for_experiment_dimension_id_fkey'),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], name='dimensions_for_experiment_experiment_id_fkey'),
    sa.PrimaryKeyConstraint('dimension_id', 'experiment_id', name='dimensions_for_experiment_pkey')
    )
    op.create_table('observations_for_experiment',
    sa.Column('observation_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('experiment_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], name='observations_for_experiment_experiment_id_fkey'),
    sa.ForeignKeyConstraint(['observation_id'], ['observations.id'], name='observations_for_experiment_observation_id_fkey'),
    sa.PrimaryKeyConstraint('observation_id', 'experiment_id', name='observations_for_experiment_pkey')
    )
    op.create_table('experiments_for_user',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('experiment_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], name='experiments_for_user_experiment_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='experiments_for_user_user_id_fkey'),
    sa.PrimaryKeyConstraint('user_id', 'experiment_id', name='experiments_for_user_pkey')
    )
    # ### end Alembic commands ###
