"""empty message

Revision ID: 4d2041ab3c22
Revises: 04c894a35632
Create Date: 2017-03-20 09:04:03.931435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d2041ab3c22'
down_revision = '04c894a35632'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('experiments_name_key', 'experiments', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('experiments_name_key', 'experiments', ['name'])
    # ### end Alembic commands ###
