"""empty message

Revision ID: 5a24b7810cfd
Revises: 6fc99156a51c
Create Date: 2017-04-03 11:28:12.311207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a24b7810cfd'
down_revision = '6fc99156a51c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('acquisitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('experiment_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('params', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('experiments', 'acq_func')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('experiments', sa.Column('acq_func', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.drop_table('acquisitions')
    # ### end Alembic commands ###
