"""empty message

Revision ID: 6fc99156a51c
Revises: 09bbaf264203
Create Date: 2017-03-26 10:49:49.263503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fc99156a51c'
down_revision = '09bbaf264203'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('experiments', sa.Column('acq_func', sa.String(length=80), nullable=True))
    op.add_column('experiments', sa.Column('n_recs', sa.Integer(), nullable=True))
    op.add_column('experiments', sa.Column('n_restarts', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('experiments', 'n_restarts')
    op.drop_column('experiments', 'n_recs')
    op.drop_column('experiments', 'acq_func')
    # ### end Alembic commands ###
