"""empty message

Revision ID: 76b53d991dee
Revises: 4d2041ab3c22
Create Date: 2017-03-20 10:01:01.559109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76b53d991dee'
down_revision = '4d2041ab3c22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('observations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('x', sa.Text(), nullable=True),
    sa.Column('y', sa.Float(), nullable=True),
    sa.Column('pending', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('observations_for_experiment',
    sa.Column('observation_id', sa.Integer(), nullable=False),
    sa.Column('experiment_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ),
    sa.ForeignKeyConstraint(['observation_id'], ['observations.id'], ),
    sa.PrimaryKeyConstraint('observation_id', 'experiment_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('observations_for_experiment')
    op.drop_table('observations')
    # ### end Alembic commands ###
