"""empty message

Revision ID: 79e4413ab6e0
Revises: 5f4314879285
Create Date: 2017-04-09 11:52:02.882275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79e4413ab6e0'
down_revision = '5f4314879285'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('experiments', 'n_recs')
    op.drop_column('experiments', 'n_restarts')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('experiments', sa.Column('n_restarts', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('experiments', sa.Column('n_recs', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
