"""empty message

Revision ID: ac2e8f487e03
Revises: 18f2c2e888bc
Create Date: 2017-03-21 19:16:18.234272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac2e8f487e03'
down_revision = '18f2c2e888bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dimensions', sa.Column('experiment_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'dimensions', 'experiments', ['experiment_id'], ['id'])
    op.add_column('experiments', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'experiments', 'users', ['user_id'], ['id'])
    op.add_column('observations', sa.Column('experiment_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'observations', 'experiments', ['experiment_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'observations', type_='foreignkey')
    op.drop_column('observations', 'experiment_id')
    op.drop_constraint(None, 'experiments', type_='foreignkey')
    op.drop_column('experiments', 'user_id')
    op.drop_constraint(None, 'dimensions', type_='foreignkey')
    op.drop_column('dimensions', 'experiment_id')
    # ### end Alembic commands ###
