"""empty message

Revision ID: cb04a13491dc
Revises: 310e89e07410
Create Date: 2017-03-23 07:58:50.111221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb04a13491dc'
down_revision = '310e89e07410'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('experiments__id_key', 'experiments', type_='unique')
    op.drop_column('experiments', '_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('experiments', sa.Column('_id', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.create_unique_constraint('experiments__id_key', 'experiments', ['_id'])
    # ### end Alembic commands ###
