"""empty message

Revision ID: d90e51b4d0b9
Revises: 5f020b8f6e19
Create Date: 2017-03-19 21:23:46.193015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd90e51b4d0b9'
down_revision = '5f020b8f6e19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dimensions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dim_type', sa.String(length=80), nullable=True),
    sa.Column('low', sa.Float(), nullable=True),
    sa.Column('high', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dimensions_for_experiment',
    sa.Column('dimension_id', sa.Integer(), nullable=False),
    sa.Column('experiment_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dimension_id'], ['dimensions.id'], ),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ),
    sa.PrimaryKeyConstraint('dimension_id', 'experiment_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dimensions_for_experiment')
    op.drop_table('dimensions')
    # ### end Alembic commands ###
